# Generated by Django 3.2.9 on 2021-11-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('postings', '0004_auto_20211102_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='readers',
            field=models.ManyToManyField(related_name='postings', to='users.User'),
        ),
    ]
